services:
  app:
    build:
      context: ./SistemaMesas
      dockerfile: ../docker/php/Dockerfile
    container_name: dewtech-app
    restart: always
    working_dir: /var/www/SistemaMesas
    command: >
      sh -c "
        sleep 5 &&
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php-fpm
      "
    volumes:
      - ./SistemaMesas:/var/www/SistemaMesas
    env_file:
      - ./SistemaMesas/.env
    environment:
      COMPOSER_HOME: /composer
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: restaurante
      DB_USERNAME: postgres
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: dewtech-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./SistemaMesas:/var/www/SistemaMesas
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    container_name: dewtech-db
    restart: always
    environment:
      - POSTGRES_DB=restaurante
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge